version: '3.8'

services:
  kafka:
    container_name: 'kafka'
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  schema-registry:
    container_name: 'schema-registry'
    image: 'bitnami/schema-registry'
    ports:
      - '8081:8081'
    depends_on:
      - kafka
    environment:
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      #      - SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD=keystore
      #      - SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD=keystore
      - SCHEMA_REGISTRY_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=none
#      - SCHEMA_REGISTRY_CLIENT_AUTHENTICATION=REQUESTED
#    volumes:
#      - ./keystore.jks:/opt/bitnami/schema-registry/certs/keystore.jks:ro
#      - ./truststore.jks:/opt/bitnami/schema-registry/certs/truststore.jks:ro
